---
title: "parameter tuning"
output: html_document
date: "2024-06-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(aida)    # remotes::install_github("michael-franke/aida-package")
library(readr)
library(furrr)
library(here)
library(philentropy)
library(here)
library(feather)


# use the aida-theme for plotting
theme_set(theme_aida())

# global color scheme / non-optimized
project_colors = c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000")

# setting theme colors globally
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = project_colors)
}
scale_fill_discrete <- function(...) {
  scale_fill_manual(..., values = project_colors)
} 
```

```{r get-data, echo=FALSE}
# get data for case study 2

urlfile="https://raw.githubusercontent.com/magpie-ea/magpie3-qa-overinfo-free-production/main/data%2Banalysis/data_PT/results_e1_human_full_anonymized_categorized_cleaned.csv"
raw_empirical_responses_2 <- read_csv(url(urlfile))
scenarios_2 <- unique(raw_empirical_responses_2$itemName)

# RSA preds over many parameter values
urlfile = "https://media.githubusercontent.com/media/hawkrobe/QA_models/main/03-current-models-webppl/data/case_study_2_parameter_search.csv"
model_preds_many_params_2 <- read_csv(url(urlfile))

########

# get data for case study 3
urlfile = "https://raw.githubusercontent.com/magpie-ea/magpie3-qa-overinfo-free-production/main/data%2Banalysis/data/results_e2_human_category_raw_cleaned.csv"
raw_empirical_responses_3 <- read_csv(url(urlfile))
scenarios_3 <- unique(raw_empirical_responses_3$itemName)

# RSA preds over many parameter values
urlfile = "https://media.githubusercontent.com/media/hawkrobe/QA_models/main/03-current-models-webppl/data/case_study_3_parameter_search.csv"
model_preds_many_params_3 <- read_csv(url(urlfile))

answerOrder <- c('taciturn', 'competitor', 'same category', 'other category', 'most similar', 'exhaustive', 'unclassified', 'other response')
```

```{r pick-params-2}
empirical_2_summary <- raw_empirical_responses_2 %>%
  filter(trial_type != "filler") %>%
  dplyr::mutate(
    answerType = dplyr::case_when(
      category == "taciturn" ~ 'taciturn',
      category == "competitor" ~ 'competitor',
      category == "sameCategory" ~ 'same category',
      category == "fullList" ~ 'exhaustive',
      category == "otherCategory" ~ 'other category',
      category == NA_character_ ~ 'other response',
      .default = "other response"
    ) %>% factor(levels = answerOrder)
  ) %>% 
  filter(answerType != "other response") %>%
  rename(scenario = itemName) %>%
  group_by(scenario, answerType) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  group_by(scenario) %>%
  mutate(human_prop = n/sum(n)) %>%
  select(-n)

model_human_2 <- model_preds_many_params_2 %>%
  select(-relevanceBetaR0) %>%
  dplyr::mutate(
    answerType = dplyr::case_when(
      support == "no.---" ~ 'taciturn',
      support == "no.competitor" ~ 'competitor',
      support == "no.competitor+sameCat" ~ 'same category',
      support == "no.sameCat" ~ 'same category',
      support == "no.competitor+otherCat" ~ 'other category',
      support == "no.otherCat" ~ 'other category',
      support == "no.sameCat+otherCat" ~ 'other response',
      support == "no.competitor+sameCat+otherCat" ~ 'exhaustive',
      .default = "other response"
    ) %>% factor(levels = answerOrder)
  ) %>%
  filter(answerType != "other response") %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight, scenario, answerType) %>%
  summarise(prob = sum(prob)) %>%
  ungroup() %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight, scenario) %>%
  mutate(prob = prob/sum(prob)) %>%
  ungroup() %>%
  complete(answerType, nesting(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight, scenario)) %>%
  left_join(empirical_2_summary, by = c("scenario", "answerType")) %>%
  replace_na(list(human_prop = 0, prob = 0))

JSD_2 <- model_human_2 %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha,  
           relevanceBetaR1, costWeight, scenario) %>%
  mutate(JSD = JSD(rbind(prob, human_prop))) %>%
  ungroup()

params_2 <- JSD_2 %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha,
           relevanceBetaR1, costWeight, scenario) %>%
  summarise(JSD = mean(JSD)) %>% # get one JSD val per scenario, not per answertype x scen
  ungroup() %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha,  
           relevanceBetaR1, costWeight) %>%
  summarise(JSD = mean(JSD)) %>% # get one JSD per set of params
  ungroup() %>%
  slice_min(n = 1, order_by = JSD)

write_csv(params_2, here("03-current-models-webppl/data/params_case_study_2.csv"))
```

```{r pick-params-3}
empirical_3_summary <- raw_empirical_responses_3 %>%
  filter(category != 'yes') %>%
  filter(category != 'other') %>%
  dplyr::mutate(
    answerType = dplyr::case_when(
      category == "taciturn" ~ 'taciturn',
      category == "competitor" ~ 'competitor',
      category == "sameCategory" ~ 'same category',
      category == "mostSimilar" ~ 'most similar',
      category == "fullList" ~ 'exhaustive',
      category == "otherCategory" ~ 'other category',
      category == NA_character_ ~ 'other response',
      .default = "other response"
    ) %>% factor(levels = answerOrder)
  ) %>% 
  rename(scenario = itemName) %>%
  group_by(scenario, answerType) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  group_by(scenario) %>%
  mutate(human_prop = n/sum(n)) %>%
  select(-n)

model_human_3 <- model_preds_many_params_3 %>%
  filter(scenario %in% scenarios_3) %>%
  select(-relevanceBetaR0) %>%
  dplyr::mutate(
    answerType = dplyr::case_when(
      support == "no.---" ~ 'taciturn',
      support == "no.competitor" ~ 'competitor',
      support == "no.mostSimilar" ~ 'most similar',
      support == "no.sameCat" ~ 'same category',
      support == "no.otherCat" ~ 'other category',
      support == "no.competitor+mostSimilar" ~ 'same category',
      support == "no.competitor+sameCat" ~ 'same category',
      support == "no.competitor+otherCat" ~ 'same category',
      support == "no.sameCat+otherCat" ~ 'same category',
      support == "no.sameCat+mostSimilar" ~ 'same category',
      support == "no.otherCat+mostSimilar" ~ 'same category',
      support == "no.competitor+sameCat+otherCat" ~ 'same category',
      support == "no.competitor+sameCat+mostSimilar" ~ 'same category',
      support == "no.competitor+otherCat+mostSimilar" ~ 'same category',
      support == "no.sameCat+otherCat+mostSimilar" ~ 'same category',
      support == "no.competitor+sameCat+otherCat+mostSimilar" ~ 'exhaustive',
      .default = "other response"
    ) %>% factor(levels = answerOrder)
  ) %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha,
           relevanceBetaR1, costWeight, answerType, scenario) %>%
  summarise(prob = sum(prob)) %>%
  ungroup() %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight, scenario) %>%
  mutate(prob = prob/sum(prob)) %>%
  ungroup() %>%
  complete(answerType, nesting(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight, scenario)) %>%
  left_join(empirical_3_summary, by = c("scenario", "answerType")) %>%
  replace_na(list(human_prop = 0, prob = 0))

JSD_3 <- model_human_3 %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight, scenario) %>%
  mutate(JSD = JSD(rbind(prob, human_prop))) %>%
  ungroup()


params_3_overall <- JSD_3 %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight, scenario) %>%
  summarise(JSD = mean(JSD)) %>% # get one JSD val per scenario, not per answertype x scen
  ungroup() %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight) %>%
  summarise(JSD = mean(JSD)) %>% # get one JSD per set of params
  ungroup() %>%
  slice_min(n = 1, order_by = JSD)

write_csv(params_3_overall, here("03-current-models-webppl/data/params_case_study_3.csv"))
```

```{r overall-2, eval = FALSE}
empirical_2_summary_overall <- raw_empirical_responses_2 %>%
  filter(trial_type != "filler") %>%
  dplyr::mutate(
    answerType = dplyr::case_when(
      category == "taciturn" ~ 'taciturn',
      category == "competitor" ~ 'competitor',
      category == "sameCategory" ~ 'same category',
      category == "fullList" ~ 'exhaustive',
      category == "otherCategory" ~ 'other category',
      category == NA_character_ ~ 'other response',
      .default = "other response"
    ) %>% factor(levels = answerOrder)
  ) %>% 
  filter(answerType != "other response") %>%
  rename(scenario = itemName) %>%
  group_by(scenario, answerType) %>%
  summarise(n = n()) %>%
  mutate(human_prop = n/sum(n)) %>%
  ungroup() %>%
  group_by(answerType) %>%
  summarise(human_prop = sum(human_prop)) %>%
  ungroup() %>%
  mutate(human_prop = human_prop/sum(human_prop)) 

model_human_2_overall <- model_preds_many_params_2 %>%
  select(-relevanceBetaR0) %>%
  dplyr::mutate(
    answerType = dplyr::case_when(
      support == "no.---" ~ 'taciturn',
      support == "no.competitor" ~ 'competitor',
      support == "no.competitor+sameCat" ~ 'same category',
      support == "no.sameCat" ~ 'same category',
      support == "no.competitor+otherCat" ~ 'other category',
      support == "no.otherCat" ~ 'other category',
      support == "no.sameCat+otherCat" ~ 'other response',
      support == "no.competitor+sameCat+otherCat" ~ 'exhaustive',
      .default = "other response"
    ) %>% factor(levels = answerOrder)
  ) %>%
  filter(answerType != "other response") %>%
  mutate(policyAlpha = cut(policyAlpha, breaks = 5),
         questionerAlpha = cut(questionerAlpha, breaks = 5),
         R1Alpha = cut(R1Alpha, breaks = 5),
         relevanceBetaR1 = cut(relevanceBetaR1, breaks = 5),
         costWeight = cut(costWeight, breaks = 5)) %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight, answerType) %>%
  summarise(prob = sum(prob)) %>%
  ungroup() %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight) %>%
  mutate(prob = prob/sum(prob)) %>%
  ungroup() %>%
  complete(answerType, nesting(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight)) %>%
  left_join(empirical_2_summary_overall, by = c("answerType")) %>%
  replace_na(list(human_prop = 0, prob = 0))

model_human_2_overall %>%
  group_by(answerType) %>%
  summarise(human = sum(human_prop), model = sum(prob))

model_human_2_overall %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight) %>%
  summarise(human = sum(human_prop), model = sum(prob)) %>% View()

JSD_2_overall <- model_human_2_overall %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha,
           relevanceBetaR1, costWeight) %>%
  mutate(JSD = JSD(rbind(prob, human_prop))) %>%
  ungroup()

params_2_overall <- JSD_2_overall %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha,
           relevanceBetaR1, costWeight) %>%
  summarise(JSD = mean(JSD)) %>% # get one JSD per set of params
  ungroup() %>%
  slice_min(n = 10, order_by = JSD)

write_csv(params_2_overall, here("03-current-models-webppl/data/params_case_study_2_overall.csv"))
```

```{r overall-3, eval = FALSE}
empirical_3_summary_overall <- raw_empirical_responses_3 %>%
  filter(category != 'yes') %>%
  filter(category != 'other') %>%
  dplyr::mutate(
    answerType = dplyr::case_when(
      category == "taciturn" ~ 'taciturn',
      category == "competitor" ~ 'competitor',
      category == "sameCategory" ~ 'same category',
      category == "mostSimilar" ~ 'most similar',
      category == "fullList" ~ 'exhaustive',
      category == "otherCategory" ~ 'other category',
      category == NA_character_ ~ 'other response',
      .default = "other response"
    ) %>% factor(levels = answerOrder)
  )  %>% 
  rename(scenario = itemName) %>%
  group_by(scenario, answerType) %>%
  summarise(n = n()) %>%
  mutate(human_prop = n/sum(n)) %>%
  ungroup() %>%
  group_by(answerType) %>%
  summarise(human_prop = sum(human_prop)) %>%
  ungroup() %>%
  mutate(human_prop = human_prop/sum(human_prop)) 

model_human_3_overall <- model_preds_many_params_3 %>%
  filter(scenario %in% scenarios_3) %>%
  select(-relevanceBetaR0) %>%
  dplyr::mutate(
    answerType = dplyr::case_when(
      support == "no.---" ~ 'taciturn',
      support == "no.competitor" ~ 'competitor',
      support == "no.mostSimilar" ~ 'most similar',
      support == "no.sameCat" ~ 'same category',
      support == "no.otherCat" ~ 'other category',
      support == "no.competitor+mostSimilar" ~ 'same category',
      support == "no.competitor+sameCat" ~ 'same category',
      support == "no.competitor+otherCat" ~ 'same category',
      support == "no.sameCat+otherCat" ~ 'same category',
      support == "no.sameCat+mostSimilar" ~ 'same category',
      support == "no.otherCat+mostSimilar" ~ 'same category',
      support == "no.competitor+sameCat+otherCat" ~ 'same category',
      support == "no.competitor+sameCat+mostSimilar" ~ 'same category',
      support == "no.competitor+otherCat+mostSimilar" ~ 'same category',
      support == "no.sameCat+otherCat+mostSimilar" ~ 'same category',
      support == "no.competitor+sameCat+otherCat+mostSimilar" ~ 'exhaustive',
      .default = "other response"
    ) %>% factor(levels = answerOrder)
  ) %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight, answerType) %>%
  summarise(prob = sum(prob)) %>%
  ungroup() %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight) %>%
  mutate(prob = prob/sum(prob)) %>%
  ungroup() %>%
  complete(answerType, nesting(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight)) %>%
  left_join(empirical_3_summary_overall, by = c("answerType")) %>%
  replace_na(list(human_prop = 0, prob = 0)) 

model_human_3_overall %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight) %>%
  summarise(human = sum(human_prop), model = sum(prob)) %>% View()

JSD_3_overall <- model_human_3_overall %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight) %>%
  mutate(JSD = JSD(rbind(prob, human_prop))) %>%
  ungroup()

params_3_overall <- JSD_3_overall %>%
  group_by(policyAlpha, questionerAlpha, R1Alpha, 
           relevanceBetaR1, costWeight) %>%
  summarise(JSD = mean(JSD)) %>% # get one JSD per set of params
  ungroup() %>%
  slice_min(n = 1, order_by = JSD)

write_csv(params_3_overall, here("03-current-models-webppl/data/params_case_study_3_overall.csv"))
```

```{r}
model_human_2_overall %>%
  select(answerType, prob, human_prop) %>%
  pivot_longer(cols = c(prob, human_prop), names_to = "agent", values_to = "prop") %>%
  ggplot(aes(x = agent, y = prop, fill = answerType)) +
    geom_bar(position="stack", stat="identity") +
  scale_x_discrete(drop = TRUE) +
  theme(axis.text.x = element_text(angle 
                                   = 45, vjust = 1, hjust=1))
model_human_3_overall %>%
  select(answerType, prob, human_prop) %>%
  pivot_longer(cols = c(prob, human_prop), names_to = "agent", values_to = "prop") %>%
  ggplot(aes(x = agent, y = prop, fill = answerType)) +
    geom_bar(position="stack", stat="identity") +
  scale_x_discrete(drop = TRUE) +
  theme(axis.text.x = element_text(angle 
                                   = 45, vjust = 1, hjust=1))

model_human_2 %>%
  filter(policyAlpha %in% params_2$policyAlpha &
         questionerAlpha %in% params_2$questionerAlpha &
         R1Alpha %in% params_2$R1Alpha &
         relevanceBetaR1 %in% params_2$relevanceBetaR1 &
         costWeight %in% params_2$costWeight) %>%
  select(answerType, prob, human_prop) %>%
  pivot_longer(cols = c(prob, human_prop), names_to = "agent", values_to = "prop") %>%
  ggplot(aes(x = agent, y = prop, fill = answerType)) +
    geom_bar(position="stack", stat="identity") +
  scale_x_discrete(drop = TRUE) +
  theme(axis.text.x = element_text(angle 
                                   = 45, vjust = 1, hjust=1))

model_human_3 %>%
  filter(policyAlpha %in% params_3$policyAlpha &
         questionerAlpha %in% params_3$questionerAlpha &
         R1Alpha %in% params_3$R1Alpha &
         relevanceBetaR1 %in% params_3$relevanceBetaR1 &
         costWeight %in% params_3$costWeight) %>%
  select(answerType, prob, human_prop) %>%
  pivot_longer(cols = c(prob, human_prop), names_to = "agent", values_to = "prop") %>%
  ggplot(aes(x = agent, y = prop, fill = answerType)) +
    geom_bar(position="stack", stat="identity") +
  scale_x_discrete(drop = TRUE) +
  theme(axis.text.x = element_text(angle 
                                   = 45, vjust = 1, hjust=1))

```

```{r}
policyAlpha = c(0,2,4,6,8,10)
questionerAlpha = c(0,2,4,6,8,10)
R1Alpha = c(0,2,4,6,8,10)
relevanceBetaR0 = c(0)
relevanceBetaR1 = c(0, 0.2, 0.4, 0.6, 0.8, 1)
costWeight = c(0, 0.2, 0.4, 0.6, 0.8, 1)

param_space <- expand_grid(policyAlpha, questionerAlpha, R1Alpha, relevanceBetaR0, relevanceBetaR1, costWeight)

param_space[1,]
```